mod p1523_count_odd_numbers_in_an_interval_range;
mod p1491_average_salary_excluding_the_minimum_and_maximum_salary;
mod p0191_number_of_1_bits;
mod p1281_subtract_the_product_and_sum_of_digits_of_an_integer;
